### ISSUE TITLE
Bug: infinity work "+1"&"-1" buttons for quote

### ISSUE THREAD

**Issue by ramzzzay** [codingteam/loglist#216] opened 2017-09-04 12:53 UTC
Everyone can click "+1"&"-1" to every quote and that will work and save the result.

**Comment by ForNeVeR** [comment] 2017-09-04 13:15
That's not a bug.

I believe what you're trying to say is that we need to implement #101 and #103, which is true.

Closing as <Not a bug|Duplicate>.

**Closed by ForNeVeR** 2017-09-04 13:15 UTC
Labels: resolution:duplicate, resolution:wontfix
