### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/loglist#35] opened 2014-10-18 08:06 UTC
Thou shalt create RSS feed.

**Comment by ForNeVeR** [comment] 2016-03-30 17:22
Finally we've decided that it's an important feature. Why was it closed in the first place? What a bizzare comment.

**Comment by rexim** [comment] 2016-03-30 17:40
wat?

**Comment by rexim** [comment] 2016-03-30 17:40
It's a duplicate of #34

**Closed** 2016-03-30 17:40 UTC
Labels: duplicate, enhancement
