### ISSUE TITLE
Reproducible infrastructure

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#135] opened 2015-08-22 10:41 UTC
I mean there is a bunch of those little things like:
- Jenkins config
- Upstart config
- Nginx config ()
- _Something else, maybe in the future?_

that are not available for anyone and not documented anywhere — I don't mean the sensitive information like passwords, I mean everything besides them.

I want our git repo to be enough to completely reproduce our infrastructure on another machine(s). When we were on Heroku it was quite easy. Heroku did everything for us.

So I think it's time to use some Configuration Management System. @ForNeVeR I believe you prefer Chef. What do you think? Should we stick with it or give a try to Puppet or Salt? (I've never used any Configuration Management System before, btw).

Also there was a suggestion (even from me) to try Foreman. But now I'm not sure about that, because I don't really understand what this shit is even after reading some docs and watching some videos on youtube. Looks like a Web-face for stuff. Don't think we need that right now.

**Comment by ForNeVeR** [comment] 2015-08-22 10:58
That's a very global task even for modern configuration management system.

First of all, we have multiple nodes our infrastructure relies on:

1. CI server (currently my Windows machine).
2. Prod server (ctor).

I am already versioning my whole Jenkins configuration in private repository (because it's full of things that cannot be published). That's a nice idea to publish the shell scripts we use for redeploying the service anyway, but this option alone will not nearly make our configuration "reproducible".

About whole ctor configuration (custom upstart tasks etc.) - I am versioning them also in my _another_ private repository, but again: that's the whole configuration, not just pieces needed to install some single service.

I don't know whether foreman will help us, but currently I see that there's many moments of our deployment that relies on our custom settings and that's too big task to make them customizable enough to reproduce somewhere.

Some options I think may be good:

1. We here provide only nice little web application. It listens the port you told him and responds with HTML / JS / whatever. When you want to deploy it for development purposes, there's an option mentioned in Readme: `sbt run`. If you want to install it into _your_ custom infrastructure - it's all up to _you_.
2. We could really extract valuable pieces of configuration and wrap them into Puppet / Chef package. Not the whole infrastructure, but the code that downloads `loglist.jar` from our release page, installs the service and allows to set up the configuration parameters.
3. We could go and create some `deb` / `rpm` / `titifuck` packages, but personally I have no experience in developing, deploying and automated configuring that.
4. We could make a Docker image (and that's a really really interesting idea, we may investigate further). That will be crossplatform enough for me, can have replaceable database connected images and such.

Regarding foreman: currently I don't see how it can be useful for us here. From what I know, it manages processes. That's all. Not environments or configurations - only processes. Maybe we will use it later, when we have multiple processes for frontend and backend. But we'll use it as a nice process management utility, not as a strategic solution in configuration management.

**Comment by rexim** [comment] 2015-08-22 11:08
@ForNeVeR Thank you very much for sharing your opinion. You have some really interesting thoughts to think about. I wanna keep this issue open for a while for discussion purpose. If I come up with something later I'll put everything here.

**Comment by ForNeVeR** [comment] 2015-08-22 11:09
I agree that we should make our configurations more clear and more easily reproducible, so you're welcome.

**Comment by ForNeVeR** [comment] 2017-07-11 09:24
Well, today I think that we have published all the infrastructural information for anyone to reproduce that.

1. [Travis CI config](https://github.com/codingteam/loglist/blob/d5e57c96ca4a708949d90af332d85f8d2f6488cd/.travis.yml)
2. [Jenkins deployment config](https://github.com/codingteam/loglist/blob/d5e57c96ca4a708949d90af332d85f8d2f6488cd/scripts/Jenkinsfile.deploy)
3. [Deployment documentation](https://github.com/codingteam/loglist/blob/d5e57c96ca4a708949d90af332d85f8d2f6488cd/docs/Deployment.md)
4. [nginx](https://github.com/codingteam/devops/tree/82d5ae1d8197444ede5033c471d398d35c0c289a/ctor/etc/nginx) and [application](https://github.com/codingteam/devops/tree/82d5ae1d8197444ede5033c471d398d35c0c289a/ctor/etc/loglist) config files from the production site
5. [systemd configuration file](https://github.com/codingteam/devops/blob/82d5ae1d8197444ede5033c471d398d35c0c289a/ctor/etc/systemd/system/loglist.service)

@rexim, I think that's all we need to make our infrastructure truly reproducible. Could we close the issue?

**Comment by rexim** [comment] 2017-07-11 15:44
@ForNeVeR feel free to close this issue. Thank you so much for your hard work on loglist maintenance!

**Comment by ForNeVeR** [comment] 2017-07-11 15:45
Okay, thanks for your collaboration.

**Closed by ForNeVeR** 2017-07-11 15:45 UTC
Labels: kind:infrastructure, kind:question

**Comment by ForNeVeR** [comment] 2017-07-11 15:46
_(one line less in my backlog; 1314 more to come)_
