### ISSUE TITLE
Loglist didn't send notification for a submitted quote

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#197] opened 2016-12-15 12:39 UTC
I submitted a quote ~20min ago and I didn't see any approver notification so far.

@ForNeVeR could you please examine the logs when you get a chance? I believe something similar happened before, but we didn't capture it in the issue tracker.

**Comment by ForNeVeR** [comment] 2016-12-15 12:47
```
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]: com.sun.mail.smtp.SMTPSendFailedException: 451 4.7.1 Service unavailable - try again later 1481804828-96krHwbkMe
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2108)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:1889)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1120)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at javax.mail.Transport.send0(Transport.java:254)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at javax.mail.Transport.send(Transport.java:174)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at helpers.Notifications$.sendApprovalMessage(Notifications.scala:64)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at helpers.Notifications$.notifyApproversAboutSuggestedQuote(Notifications.scala:23)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at controllers.SuggestedQuotes$$anonfun$addQuote$1$$anonfun$apply$3.apply(SuggestedQuotes.scala:43)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at controllers.SuggestedQuotes$$anonfun$addQuote$1$$anonfun$apply$3.apply(SuggestedQuotes.scala:36)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.data.Form.fold(Form.scala:139)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at controllers.SuggestedQuotes$$anonfun$addQuote$1.apply(SuggestedQuotes.scala:31)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at controllers.SuggestedQuotes$$anonfun$addQuote$1.apply(SuggestedQuotes.scala:28)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at helpers.ActionWithTx$$anonfun$1.apply(ActionWithTx.scala:13)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at helpers.ActionWithTx$$anonfun$1.apply(ActionWithTx.scala:12)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scalikejdbc.DBConnection$$anonfun$_localTx$1$1.apply(DBConnection.scala:252)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scala.util.control.Exception$Catch.apply(Exception.scala:103)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scalikejdbc.DBConnection$class._localTx$1(DBConnection.scala:250)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scalikejdbc.DBConnection$class.localTx(DBConnection.scala:258)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scalikejdbc.DB.localTx(DB.scala:75)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scalikejdbc.DB$$anonfun$localTx$1.apply(DB.scala:257)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scalikejdbc.DB$$anonfun$localTx$1.apply(DB.scala:256)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scalikejdbc.LoanPattern$class.using(LoanPattern.scala:33)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scalikejdbc.DB$.using(DB.scala:150)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scalikejdbc.DB$.localTx(DB.scala:256)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at helpers.ActionWithTx$.invokeBlock(ActionWithTx.scala:12)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at helpers.ActionWithTx$.invokeBlock(ActionWithTx.scala:10)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scala.Option.map(Option.scala:145)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
Dec 15 07:27:08 xmpp1 loglist-jvm[16122]:         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by rexim** [comment] 2016-12-15 12:49
@ForNeVeR aha, cool! Thanks! I think we should handle that somehow. I'll try to convert this incident into an enhancement a bit later.

**Comment by ForNeVeR** [comment] 2016-12-15 12:50
Maybe we'll need a service to send the mail asynchronously. Usually my projects at work have one.

**Comment by Minoru** [comment] 2020-10-25 20:20
This is a duplicate of #82, closing.

**Closed by Minoru** 2020-10-25 20:20 UTC
Labels: kind:incident
